<h1 style="text-align:center; color:black; font-weight:bold;">
Thực hành dự án cuối khóa Google Data Analytics
</h1>

### Tóm tắt nội dung thực hiện trong đoạn mã dưới.
- Thực hiện gộp 12 file dữ liệu của 12 tháng về dữ liệu các chuyến đi xe đạp
- Khám phá các thông tin cơ bản của tập dữ liệu và các thuộc tính
- Loại bỏ 6428 dòng dữ liệu có thời gian di chuyển xe đạp âm (< 0s) và thời gian thuê lớn hơn 1 ngày ( 24h).

## I, Gọi thư viện, đọc dữ liệu

In [1]:
import pandas as pd

In [2]:
path = "C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202406-divvy-tripdata.csv"
df = pd.read_csv(path)
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CDE6023BE6B11D2F,electric_bike,2024-06-11 17:20:06.289,2024-06-11 17:21:39.464,NaN,NaN,NaN,NaN,41.890000,-87.650000,41.890000,-87.650000,casual
1,462B48CD292B6A18,electric_bike,2024-06-11 17:19:21.567,2024-06-11 17:19:36.377,NaN,NaN,NaN,NaN,41.890000,-87.650000,41.890000,-87.650000,casual
2,9CFB6A858D23ABF7,electric_bike,2024-06-11 17:25:27.089,2024-06-11 17:30:13.035,NaN,NaN,NaN,NaN,41.930000,-87.650000,41.940000,-87.650000,casual
3,6365EFEB64231153,electric_bike,2024-06-11 11:53:50.769,2024-06-11 12:08:13.382,NaN,NaN,NaN,NaN,41.880000,-87.640000,41.880000,-87.640000,casual
4,BA0323C33134CBA8,electric_bike,2024-06-11 00:11:08.237,2024-06-11 00:11:22.998,NaN,NaN,NaN,NaN,41.940000,-87.640000,41.940000,-87.640000,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
710716,1D1EBE57758FB1EE,electric_bike,2024-06-11 08:25:42.325,2024-06-11 08:33:43.928,Ravenswood Ave & Lawrence Ave,TA1309000066,Campbell Ave & Montrose Ave,15623,41.968466,-87.674225,41.961524,-87.691177,member
710717,2F63E9CD01D79515,electric_bike,2024-06-24 11:40:44.516,2024-06-24 11:42:09.949,Damen Ave & Leland Ave,TA1307000158,NaN,NaN,41.967121,-87.679127,41.970000,-87.670000,member
710718,97D225818F9C7AC3,electric_bike,2024-06-30 10:43:32.975,2024-06-30 10:45:45.087,Damen Ave & Leland Ave,TA1307000158,NaN,NaN,41.967154,-87.679091,41.970000,-87.680000,member
710719,C8D2A48B901F7399,electric_bike,2024-06-11 18:20:40.861,2024-06-11 18:29:04.920,Pine Grove Ave & Irving Park Rd,TA1308000022,NaN,NaN,41.954404,-87.647983,41.930000,-87.640000,member
710720,C372E7A1A7BA19D4,electric_bike,2024-06-15 15:48:49.207,2024-06-15 15:52:31.365,Ravenswood Ave & Lawrence Ave,TA1309000066,NaN,NaN,41.968486,-87.674196,41.970000,-87.660000,member

### Tách biến path để cộng thêm tên file

In [3]:
path = "C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/"
df = pd.read_csv(path + "202407-divvy-tripdata.csv")
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,2658E319B13141F9,electric_bike,2024-07-11 08:15:14.784,2024-07-11 08:17:56.335,NaN,NaN,NaN,NaN,41.800000,-87.590000,41.790000,-87.590000,casual
1,B2176315168A47CE,electric_bike,2024-07-11 15:45:07.851,2024-07-11 16:06:04.243,NaN,NaN,NaN,NaN,41.790000,-87.600000,41.800000,-87.590000,casual
2,C2A9D33DF7EBB422,electric_bike,2024-07-11 08:24:48.192,2024-07-11 08:28:05.237,NaN,NaN,NaN,NaN,41.790000,-87.590000,41.790000,-87.600000,casual
3,8BFEA406DF01D8AD,electric_bike,2024-07-11 08:46:06.864,2024-07-11 09:14:11.664,NaN,NaN,NaN,NaN,41.880000,-87.640000,41.900000,-87.670000,casual
4,ECD3EF02E5EB73B6,electric_bike,2024-07-11 18:18:16.588,2024-07-11 18:30:20.288,NaN,NaN,NaN,NaN,41.950000,-87.640000,41.910000,-87.620000,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
748957,59C1028E4ADAFF34,classic_bike,2024-07-26 15:05:14.866,2024-07-26 15:14:31.714,Clark St & Newport St,632,Southport Ave & Clark St,TA1308000047,41.944540,-87.654678,41.957081,-87.664199,casual
748958,73A048C72FF98D52,electric_bike,2024-07-06 15:58:16.058,2024-07-06 16:07:22.019,Clark St & Newport St,632,Southport Ave & Clark St,TA1308000047,41.944428,-87.654805,41.957081,-87.664199,casual
748959,0BEA43E696F6B39C,classic_bike,2024-07-03 17:11:45.420,2024-07-03 17:57:09.028,Dearborn St & Van Buren St,624,Cornell Ave & Hyde Park Blvd,KA1503000007,41.876268,-87.629155,41.802406,-87.586924,casual
748960,552678ADCEF46B37,classic_bike,2024-07-03 17:09:13.869,2024-07-03 17:17:50.359,Dearborn St & Van Buren St,624,Clinton St & Madison St,TA1305000032,41.876268,-87.629155,41.882752,-87.641190,member
748961,038CFD31016F2C88,classic_bike,2024-07-18 13:36:41.487,2024-07-18 13:43:55.335,Dearborn St & Van Buren St,624,Clinton St & Madison St,TA1305000032,41.876268,-87.629155,41.882752,-87.641190,member

## II, Nối 12 tập dữ liệu

In [4]:
# thư viện oprating system: thao tác với hệ điều hành, đổi tập tin..
import os

In [5]:
# Hiển thị tên 12 tập dữ liệu
os.listdir(path)

['202406-divvy-tripdata.csv',
 '202407-divvy-tripdata.csv',
 '202408-divvy-tripdata.csv',
 '202409-divvy-tripdata.csv',
 '202410-divvy-tripdata.csv',
 '202411-divvy-tripdata.csv',
 '202412-divvy-tripdata.csv',
 '202501-divvy-tripdata.csv',
 '202502-divvy-tripdata.csv',
 '202503-divvy-tripdata.csv',
 '202504-divvy-tripdata.csv',
 '202505-divvy-tripdata.csv',
 '__MACOSX']

In [6]:
filepaths = []
for file in os.listdir(path):
    if file.endswith("csv"):
        filepath = path + file
        filepaths.append(filepath)
    
print(filepaths)

['C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202406-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202407-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202408-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202409-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202410-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202411-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202412-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202501-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202502-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202503-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202504-divvy-tripdata.csv', 'C:/Users/nxh/Documents/3 - Luyện tập Python Jupyter/Case Study 1/Data Raw/202505-divvy-tripdata.csv']

In [7]:
df_test1 = pd.read_csv(filepaths[1])
df_test1

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,2658E319B13141F9,electric_bike,2024-07-11 08:15:14.784,2024-07-11 08:17:56.335,NaN,NaN,NaN,NaN,41.800000,-87.590000,41.790000,-87.590000,casual
1,B2176315168A47CE,electric_bike,2024-07-11 15:45:07.851,2024-07-11 16:06:04.243,NaN,NaN,NaN,NaN,41.790000,-87.600000,41.800000,-87.590000,casual
2,C2A9D33DF7EBB422,electric_bike,2024-07-11 08:24:48.192,2024-07-11 08:28:05.237,NaN,NaN,NaN,NaN,41.790000,-87.590000,41.790000,-87.600000,casual
3,8BFEA406DF01D8AD,electric_bike,2024-07-11 08:46:06.864,2024-07-11 09:14:11.664,NaN,NaN,NaN,NaN,41.880000,-87.640000,41.900000,-87.670000,casual
4,ECD3EF02E5EB73B6,electric_bike,2024-07-11 18:18:16.588,2024-07-11 18:30:20.288,NaN,NaN,NaN,NaN,41.950000,-87.640000,41.910000,-87.620000,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
748957,59C1028E4ADAFF34,classic_bike,2024-07-26 15:05:14.866,2024-07-26 15:14:31.714,Clark St & Newport St,632,Southport Ave & Clark St,TA1308000047,41.944540,-87.654678,41.957081,-87.664199,casual
748958,73A048C72FF98D52,electric_bike,2024-07-06 15:58:16.058,2024-07-06 16:07:22.019,Clark St & Newport St,632,Southport Ave & Clark St,TA1308000047,41.944428,-87.654805,41.957081,-87.664199,casual
748959,0BEA43E696F6B39C,classic_bike,2024-07-03 17:11:45.420,2024-07-03 17:57:09.028,Dearborn St & Van Buren St,624,Cornell Ave & Hyde Park Blvd,KA1503000007,41.876268,-87.629155,41.802406,-87.586924,casual
748960,552678ADCEF46B37,classic_bike,2024-07-03 17:09:13.869,2024-07-03 17:17:50.359,Dearborn St & Van Buren St,624,Clinton St & Madison St,TA1305000032,41.876268,-87.629155,41.882752,-87.641190,member
748961,038CFD31016F2C88,classic_bike,2024-07-18 13:36:41.487,2024-07-18 13:43:55.335,Dearborn St & Van Buren St,624,Clinton St & Madison St,TA1305000032,41.876268,-87.629155,41.882752,-87.641190,member

* cách dùng concat gộp dataframe
* frames = [df1, df2, df3]
* result = pd.concat(fram)

In [8]:
frames = []
# filepaths = [] bỏ do không cần đường dẫn nữa
for file in os.listdir(path):
    if file.endswith("csv"):
        filepath = path + file
        # filepaths.append(filepath): không cần  
        df1 = pd.read_csv(filepath)
        frames.append(df1)
# print(filepaths)
result = pd.concat(frames)
result

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CDE6023BE6B11D2F,electric_bike,2024-06-11 17:20:06.289,2024-06-11 17:21:39.464,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual
1,462B48CD292B6A18,electric_bike,2024-06-11 17:19:21.567,2024-06-11 17:19:36.377,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual
2,9CFB6A858D23ABF7,electric_bike,2024-06-11 17:25:27.089,2024-06-11 17:30:13.035,NaN,NaN,NaN,NaN,41.93,-87.65,41.94,-87.65,casual
3,6365EFEB64231153,electric_bike,2024-06-11 11:53:50.769,2024-06-11 12:08:13.382,NaN,NaN,NaN,NaN,41.88,-87.64,41.88,-87.64,casual
4,BA0323C33134CBA8,electric_bike,2024-06-11 00:11:08.237,2024-06-11 00:11:22.998,NaN,NaN,NaN,NaN,41.94,-87.64,41.94,-87.64,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
502451,4BE8507E20D9DC14,electric_bike,2025-05-16 10:43:14.778,2025-05-16 11:05:16.517,NaN,NaN,NaN,NaN,41.99,-87.66,41.96,-87.65,member
502452,F848B34F2E984E64,electric_bike,2025-05-15 21:58:39.734,2025-05-15 22:09:02.872,NaN,NaN,NaN,NaN,41.94,-87.64,41.92,-87.64,member
502453,BAAE2021F788A1B3,electric_bike,2025-05-29 06:01:28.948,2025-05-29 06:06:53.885,NaN,NaN,NaN,NaN,41.90,-87.63,41.90,-87.64,member
502454,FC511D59826DDAB8,electric_bike,2025-05-29 17:01:45.584,2025-05-29 17:14:59.173,NaN,NaN,NaN,NaN,41.88,-87.64,41.90,-87.63,member
502455,401977A31ECEC6B0,electric_bike,2025-05-08 13:41:14.415,2025-05-08 13:47:04.042,NaN,NaN,NaN,NaN,41.98,-87.70,41.98,-87.69,member

In [9]:
# Kiểm tra độ dài từng tập tin
frames = []
all_length = []
for file in os.listdir(path):
    if file.endswith("csv"):
        filepath = path + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)
        length_1month = len(df1.index)
        all_length.append(length_1month)

In [10]:
print(all_length)

[710721, 748962, 755639, 821276, 616281, 335075, 178372, 138689, 151880, 298155, 371341, 502456]

In [11]:
# In ra độ dài tập tin khi sau khi nối
print(sum(all_length))

5628847

In [12]:
df = result

## III, Khám phá, dọn dẹp dữ liệu

In [13]:
# Xem 5 dòng đầu tiên
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CDE6023BE6B11D2F,electric_bike,2024-06-11 17:20:06.289,2024-06-11 17:21:39.464,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual
1,462B48CD292B6A18,electric_bike,2024-06-11 17:19:21.567,2024-06-11 17:19:36.377,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual
2,9CFB6A858D23ABF7,electric_bike,2024-06-11 17:25:27.089,2024-06-11 17:30:13.035,NaN,NaN,NaN,NaN,41.93,-87.65,41.94,-87.65,casual
3,6365EFEB64231153,electric_bike,2024-06-11 11:53:50.769,2024-06-11 12:08:13.382,NaN,NaN,NaN,NaN,41.88,-87.64,41.88,-87.64,casual
4,BA0323C33134CBA8,electric_bike,2024-06-11 00:11:08.237,2024-06-11 00:11:22.998,NaN,NaN,NaN,NaN,41.94,-87.64,41.94,-87.64,casual

In [14]:
# Xem 5 dòng cuối
df.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
502451,4BE8507E20D9DC14,electric_bike,2025-05-16 10:43:14.778,2025-05-16 11:05:16.517,NaN,NaN,NaN,NaN,41.99,-87.66,41.96,-87.65,member
502452,F848B34F2E984E64,electric_bike,2025-05-15 21:58:39.734,2025-05-15 22:09:02.872,NaN,NaN,NaN,NaN,41.94,-87.64,41.92,-87.64,member
502453,BAAE2021F788A1B3,electric_bike,2025-05-29 06:01:28.948,2025-05-29 06:06:53.885,NaN,NaN,NaN,NaN,41.90,-87.63,41.90,-87.64,member
502454,FC511D59826DDAB8,electric_bike,2025-05-29 17:01:45.584,2025-05-29 17:14:59.173,NaN,NaN,NaN,NaN,41.88,-87.64,41.90,-87.63,member
502455,401977A31ECEC6B0,electric_bike,2025-05-08 13:41:14.415,2025-05-08 13:47:04.042,NaN,NaN,NaN,NaN,41.98,-87.70,41.98,-87.69,member

In [15]:
# Kiểm tra kích thước dữ liệu
print("Số dòng và số cột:", df.shape)

Số dòng và số cột: (5628847, 13)

In [16]:
df.reset_index(drop=True, inplace=True)

In [17]:
df.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
5628842,4BE8507E20D9DC14,electric_bike,2025-05-16 10:43:14.778,2025-05-16 11:05:16.517,NaN,NaN,NaN,NaN,41.99,-87.66,41.96,-87.65,member
5628843,F848B34F2E984E64,electric_bike,2025-05-15 21:58:39.734,2025-05-15 22:09:02.872,NaN,NaN,NaN,NaN,41.94,-87.64,41.92,-87.64,member
5628844,BAAE2021F788A1B3,electric_bike,2025-05-29 06:01:28.948,2025-05-29 06:06:53.885,NaN,NaN,NaN,NaN,41.90,-87.63,41.90,-87.64,member
5628845,FC511D59826DDAB8,electric_bike,2025-05-29 17:01:45.584,2025-05-29 17:14:59.173,NaN,NaN,NaN,NaN,41.88,-87.64,41.90,-87.63,member
5628846,401977A31ECEC6B0,electric_bike,2025-05-08 13:41:14.415,2025-05-08 13:47:04.042,NaN,NaN,NaN,NaN,41.98,-87.70,41.98,-87.69,member

In [18]:
print(df.index)

RangeIndex(start=0, stop=5628847, step=1)

In [19]:
# Xem thông tin kiểu dữ liệu và null
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5628847 entries, 0 to 5628846
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 558.3+ MB

In [20]:
df.describe()

          start_lat     start_lng       end_lat       end_lng
count  5.628847e+06  5.628847e+06  5.622681e+06  5.622681e+06
mean   4.190214e+01 -8.764625e+01  4.190255e+01 -8.764650e+01
std    4.455484e-02  2.751892e-02  5.625243e-02  1.158685e-01
min    4.164000e+01 -8.791000e+01  1.606000e+01 -1.440500e+02
25%    4.188096e+01 -8.766000e+01  4.188096e+01 -8.766000e+01
50%    4.189679e+01 -8.764174e+01  4.189766e+01 -8.764238e+01
75%    4.192955e+01 -8.762954e+01  4.193000e+01 -8.762963e+01
max    4.207000e+01 -8.752000e+01  8.796000e+01  1.525300e+02

In [21]:
df.describe(include=['object'])

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual
count,5628847,5628847,5628847,5628847,4546902,4546902,4518107,4518107,5628847
unique,5628847,3,5627717,5626976,1869,1785,1872,1787,2
top,CDE6023BE6B11D2F,electric_bike,2024-06-24 14:10:54.002,2024-10-20 11:18:09.462,Streeter Dr & Grand Ave,13022,Streeter Dr & Grand Ave,13022,member
freq,1,3071374,2,17,60785,60785,62041,62041,3564561

In [22]:
df['rideable_type'].value_counts()

electric_bike       3071374
classic_bike        2413136
electric_scooter     144337
Name: rideable_type, dtype: int64

In [23]:
df['member_casual'].value_counts()

member    3564561
casual    2064286
Name: member_casual, dtype: int64

In [24]:
df['start_station_name'].value_counts().head(10)

Streeter Dr & Grand Ave               60785
Kingsbury St & Kinzie St              41467
DuSable Lake Shore Dr & Monroe St     40776
Michigan Ave & Oak St                 37029
DuSable Lake Shore Dr & North Blvd    37010
Clark St & Elm St                     34029
Clinton St & Washington Blvd          32406
Clinton St & Madison St               31962
Millennium Park                       31437
Wells St & Concord Ln                 30388
Name: start_station_name, dtype: int64

In [25]:
df['member_casual'].value_counts(normalize=True) * 100

member    63.326664
casual    36.673336
Name: member_casual, dtype: float64

In [26]:
df.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1081945
start_station_id      1081945
end_station_name      1110740
end_station_id        1110740
start_lat                   0
start_lng                   0
end_lat                  6166
end_lng                  6166
member_casual               0
dtype: int64

In [27]:
# Truyển kiều dữ liệu của thời gian bắt đầu kết thúc -> sang định dạng ngày tháng để phục vụ tính toán
df['started_at'] = pd.to_datetime(df['started_at'])
df['ended_at'] = pd.to_datetime(df['ended_at'])

In [28]:
df['ride_length'] = (df['ended_at'] - df['started_at']).dt.total_seconds() / 60

df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
0,CDE6023BE6B11D2F,electric_bike,2024-06-11 17:20:06.289,2024-06-11 17:21:39.464,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual,1.552917
1,462B48CD292B6A18,electric_bike,2024-06-11 17:19:21.567,2024-06-11 17:19:36.377,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual,0.246833
2,9CFB6A858D23ABF7,electric_bike,2024-06-11 17:25:27.089,2024-06-11 17:30:13.035,NaN,NaN,NaN,NaN,41.93,-87.65,41.94,-87.65,casual,4.765767
3,6365EFEB64231153,electric_bike,2024-06-11 11:53:50.769,2024-06-11 12:08:13.382,NaN,NaN,NaN,NaN,41.88,-87.64,41.88,-87.64,casual,14.376883
4,BA0323C33134CBA8,electric_bike,2024-06-11 00:11:08.237,2024-06-11 00:11:22.998,NaN,NaN,NaN,NaN,41.94,-87.64,41.94,-87.64,casual,0.246017

In [29]:
# Kiểm tra số chuyến có thời gian âm
count_negative = df[df['ride_length'] < 0].shape[0]
print(f"Số chuyến có thời gian âm: {count_negative}")

# Kiểm tra số chuyến có thời gian lớn hơn 24 giờ (1440 phút)
count_over_24h = df[df['ride_length'] > 1440].shape[0]
print(f"Số chuyến có thời gian trên 24 giờ: {count_over_24h}")

Số chuyến có thời gian âm: 43
Số chuyến có thời gian trên 24 giờ: 6385

In [30]:
# Xem chi tiết các chuyến có thời gian âm
df[df['ride_length'] < 0]

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
3657369,A3C86101B94DCF83,classic_bike,2024-11-03 01:53:34.934,2024-11-03 01:04:55.434,Western Ave & Walton St,KA1504000103,Damen Ave & Charleston St,13288,41.898418,-87.686596,41.920082,-87.677855,member,-48.658333
3659357,9E3880C1B94EAB39,electric_bike,2024-11-03 01:48:07.988,2024-11-03 01:08:20.603,Kingsbury St & Kinzie St,KA1503000043,Clark St & Schiller St,TA1309000024,41.889177,-87.638506,41.907993,-87.631501,casual,-39.789750
3662262,A21F9A727675300F,electric_bike,2024-11-03 01:53:22.726,2024-11-03 01:06:40.133,Western Ave & Walton St,KA1504000103,Kedzie Ave & Milwaukee Ave,13085,41.898418,-87.686596,41.928999,-87.708030,member,-46.709883
3669198,61C2AE038C0D67AB,classic_bike,2024-11-03 01:25:33.243,2024-11-03 01:21:30.713,DuSable Lake Shore Dr & Monroe St,13300,Financial Pl & Ida B Wells Dr,SL-010,41.880958,-87.616743,41.875024,-87.633094,casual,-4.042167
3684970,E44DD2F8C07D6B2D,electric_bike,2024-11-03 01:49:17.648,2024-11-03 01:02:39.700,NaN,NaN,NaN,NaN,41.920000,-87.650000,41.910000,-87.630000,member,-46.632467
3687068,F147973D700AA375,electric_bike,2024-11-03 01:50:02.506,2024-11-03 01:03:37.247,Larrabee St & Oak St,KA1504000116,LaSalle Dr & Huron St,KP1705001026,41.900219,-87.642985,41.894877,-87.632326,casual,-46.420983
3703323,F600DA96D6308ABF,electric_bike,2024-11-03 01:55:22.919,2024-11-03 01:00:36.080,Aberdeen St & Jackson Blvd,13157,Clinton St & Lake St,13021,41.877726,-87.654787,41.885637,-87.641823,casual,-54.780650
3705150,CFED9E2BF0A7F676,electric_bike,2024-11-03 01:50:18.246,2024-11-03 01:03:39.105,Larrabee St & Oak St,KA1504000116,LaSalle Dr & Huron St,KP1705001026,41.900219,-87.642985,41.894877,-87.632326,member,-46.652350
3713730,BB4F8E728A4714E3,classic_bike,2024-11-03 01:55:10.885,2024-11-03 01:02:13.083,Clark St & Bryn Mawr Ave,KA1504000151,Damen Ave & Foster Ave,KA1504000149,41.983593,-87.669154,41.975811,-87.679510,casual,-52.963367
3718110,5DD72265826A6FC0,classic_bike,2024-11-03 01:53:34.793,2024-11-03 01:11:24.271,Wilton Ave & Belmont Ave,TA1307000134,Broadway & Berwyn Ave,13109,41.940232,-87.652944,41.978361,-87.659789,casual,-42.175367
3738894,1ED3B2ACE0FE3C99,electric_bike,2024-11-03 01:59:24.648,2024-11-03 01:03:23.346,NaN,NaN,W Armitage Ave & N Sheffield Ave,20254.0,41.920000,-87.670000,41.917805,-87.653449,member,-56.021700
3747538,76C64FC8024DA2AC,electric_bike,2024-11-03 01:54:39.214,2024-11-03 01:24:40.840,NaN,NaN,Wabash Ave & 16th St,SL-012,41.890000,-87.650000,41.860384,-87.625813,casual,-29.972900
3752418,CB6B83A69815601E,classic_bike,2024-11-03 01:25:14.083,2024-11-03 01:21:26.779,DuSable Lake Shore Dr & Monroe St,13300,Financial Pl & Ida B Wells Dr,SL-010,41.880958,-87.616743,41.875024,-87.633094,casual,-3.788400
3755392,BCD7AB1DE9ACBAB0,classic_bike,2024-11-03 01:48:42.787,2024-11-03 01:04:50.681,Milwaukee Ave & Wabansia Ave,13243,Milwaukee Ave & Rockwell St,13242,41.912616,-87.681391,41.920196,-87.692659,casual,-43.868433
3765633,B4DFEDC4D2BCE650,classic_bike,2024-11-03 01:24:08.760,2024-11-03 01:21:28.841,DuSable Lake Shore Dr & Monroe St,13300,Financial Pl & Ida B Wells Dr,SL-010,41.880958,-87.616743,41.875024,-87.633094,casual,-2.665317
3765634,539D35F4E7FE1D13,classic_bike,2024-11-03 01:27:08.699,2024-11-03 01:21:32.265,DuSable Lake Shore Dr & Monroe St,13300,Financial Pl & Ida B Wells Dr,SL-010,41.880958,-87.616743,41.875024,-87.633094,casual,-5.607233
3765635,CC11A50F0125A6B8,classic_bike,2024-11-03 01:26:02.313,2024-11-03 01:21:39.906,DuSable Lake Shore Dr & Monroe St,13300,Financial Pl & Ida B Wells Dr,SL-010,41.880958,-87.616743,41.875024,-87.633094,casual,-4.373450
3778290,205F5CAF36F92EBF,electric_bike,2024-11-03 01:59:08.999,2024-11-03 01:13:02.165,Laflin St & Cullerton St,13307,Ogden Ave & Chicago Ave,TA1305000020,41.854915,-87.663560,41.896362,-87.654061,casual,-46.113900
3791212,143F5D35258E8E3F,electric_bike,2024-11-03 01:57:10.531,2024-11-03 01:22:58.936,Kedvale Ave & Peterson Ave,24159,Public Rack - Cicero & Rosemont,1210.0,41.990076,-87.731707,41.995567,-87.748640,casual,-34.193250
3793069,89B05E7D874903B3,electric_bike,2024-11-03 01:56:19.891,2024-11-03 01:02:18.167,NaN,NaN,Humboldt Blvd & Armitage Ave,15651,41.920000,-87.720000,41.917513,-87.701809,casual,-54.028733
3804651,5698BC27B89298D2,electric_bike,2024-11-03 01:48:08.185,2024-11-03 01:08:24.249,Kingsbury St & Kinzie St,KA1503000043,Clark St & Schiller St,TA1309000024,41.889177,-87.638506,41.907993,-87.631501,casual,-39.732267
3818496,54E0B99065907777,electric_bike,2024-11-03 01:39:41.272,2024-11-03 01:08:34.751,California Ave & Milwaukee Ave,13084,California Ave & Francis Pl,13259,41.922735,-87.697167,41.918491,-87.697423,member,-31.108683
3818514,BCF09672DBEAE929,electric_bike,2024-11-03 01:57:11.474,2024-11-03 01:08:52.560,NaN,NaN,California Ave & Francis Pl,13259,41.920000,-87.690000,41.918491,-87.697423,casual,-48.315233
3846980,2CD1341FCC0AECA8,classic_bike,2024-11-03 01:47:53.346,2024-11-03 01:04:05.631,Greenview Ave & Fullerton Ave,TA1307000001,Sheffield Ave & Kingsbury St,13154,41.925330,-87.665800,41.910522,-87.653106,member,-43.795250
3854567,4D21421A494FA0DF,electric_bike,2024-11-03 01:54:51.426,2024-11-03 01:06:04.198,NaN,NaN,Central Park Ave & Elbridge Ave,15644,41.910000,-87.680000,41.935337,-87.716889,member,-48.787133
3855676,C2D0EA867C94CB05,electric_bike,2024-11-03 01:57:10.166,2024-11-03 01:05:39.411,Clark St & Elm St,TA1307000039,Sheffield Ave & Webster Ave,TA1309000033,41.902973,-87.631280,41.921540,-87.653818,member,-51.512583
3863733,FE757D0F98D5DE20,classic_bike,2024-11-03 01:58:57.043,2024-11-03 01:09:01.069,Woodlawn Ave & 55th St,TA1307000164,Woodlawn Ave & 55th St,TA1307000164,41.795264,-87.596471,41.795264,-87.596471,member,-49.932900
3864363,583714F53028385C,electric_bike,2024-11-03 01:44:26.689,2024-11-03 01:02:41.956,Racine Ave & Fullerton Ave,TA1306000026,Wells St & Concord Ln,TA1308000050,41.925566,-87.658416,41.912133,-87.634656,member,-41.745550
3889052,402C16763196CCD0,electric_bike,2024-11-03 01:43:11.030,2024-11-03 01:13:12.746,NaN,NaN,Clark St & Wrightwood Ave,TA1305000014,41.890000,-87.630000,41.929546,-87.643118,member,-29.971400
3902127,CF11AD1AA5499FD6,classic_bike,2024-11-03 01:57:59.221,2024-11-03 01:02:33.679,Clark St & Berwyn Ave,KA1504000146,Broadway & Ridge Ave,15578,41.978031,-87.668565,41.984045,-87.660274,member,-55.425700
3914155,0F650CF4B8BFC921,electric_bike,2024-11-03 01:58:43.331,2024-11-03 01:04:26.399,NaN,NaN,NaN,NaN,41.940000,-87.640000,41.930000,-87.640000,casual,-54.282200
3923312,E062D2E12BA37706,electric_bike,2024-11-03 01:40:30.231,2024-11-03 01:07:47.204,Halsted St & Roscoe St,TA1309000025,NaN,NaN,41.943670,-87.648950,41.940000,-87.640000,member,-32.717117
3927761,2D4D1BA90E81EDF3,electric_bike,2024-11-03 01:47:51.441,2024-11-03 01:10:30.589,Dayton St & North Ave,13058,NaN,NaN,41.910578,-87.649422,41.910000,-87.730000,casual,-37.347533
3930187,6E973218589BD118,classic_bike,2024-11-03 01:55:58.187,2024-11-03 01:03:34.688,Milwaukee Ave & Wabansia Ave,13243,California Ave & Milwaukee Ave,13084,41.912616,-87.681391,41.922695,-87.697153,member,-52.391650
3939944,614D652A7CCB5197,electric_bike,2024-11-03 01:59:30.206,2024-11-03 01:10:34.916,NaN,NaN,NaN,NaN,41.950000,-87.660000,41.930000,-87.640000,member,-48.921500
3941334,B594A121A0AB6EED,electric_bike,2024-11-03 01:53:44.330,2024-11-03 01:00:00.174,NaN,NaN,NaN,NaN,41.950000,-87.650000,41.970000,-87.660000,member,-53.735933
3941686,BC3747A7FCC81F68,electric_bike,2024-11-03 01:47:35.645,2024-11-03 01:03:29.255,NaN,NaN,NaN,NaN,41.950000,-87.650000,41.950000,-87.720000,member,-44.106500
3950596,9F9F6501E97E5789,electric_bike,2024-11-03 01:47:47.690,2024-11-03 01:02:42.884,Sheffield Ave & Fullerton Ave,TA1306000016,NaN,NaN,41.924781,-87.653626,41.910000,-87.630000,member,-45.080100
3956702,3A587733462DA2C3,electric_bike,2024-11-03 01:57:49.758,2024-11-03 01:17:29.247,Dearborn Pkwy & Delaware Pl,TA1307000128,NaN,NaN,41.898969,-87.629912,41.950000,-87.670000,casual,-40.341850
3962627,4BD1F0EE07E79421,classic_bike,2024-11-03 01:51:30.818,2024-11-03 01:16:39.875,Clark St & Wrightwood Ave,TA1305000014,Kildare Ave & Montrose Ave,KA1706005015,41.929546,-87.643118,41.961080,-87.735690,casual,-34.849050
3969314,C497066FD1D05EEE,electric_bike,2024-11-03 01:58:02.303,2024-11-03 01:03:32.261,NaN,NaN,Clark St & Elm St,TA1307000039,41.910000,-87.640000,41.902973,-87.631280,casual,-54.500700
3969529,6D8CC446C1251515,electric_bike,2024-11-03 01:52:30.180,2024-11-03 01:06:44.950,Ashland Ave & Blackhawk St,13224,Damen Ave & Cullerton St,13089,41.907066,-87.667252,41.854967,-87.675700,casual,-45.753833
3986541,E8F98270528A59CC,electric_bike,2024-11-03 01:54:55.644,2024-11-03 01:03:12.879,NaN,NaN,Wells St & Institute Pl,22001,41.880000,-87.640000,41.897380,-87.634420,member,-51.712750

In [31]:
# Xem chi tiết các chuyến trên 24 giờ
df[df['ride_length'] > 1440].head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
766,AB15DC7A423435DF,classic_bike,2024-06-11 15:30:32.184,2024-06-12 16:30:17.256,Cottage Grove Ave & 51st St,TA1309000067,NaN,NaN,41.803038,-87.606615,NaN,NaN,casual,1499.751200
18971,100F27EC3569E83B,classic_bike,2024-06-14 20:52:01.904,2024-06-15 21:27:02.900,Clark St & Lake St,KA1503000012,State St & Kinzie St,13050,41.886021,-87.630876,41.889375,-87.627077,casual,1475.016600
44883,65B70111959D1213,classic_bike,2024-06-08 13:06:27.477,2024-06-09 13:58:31.566,Southport Ave & Wrightwood Ave,TA1307000113,Southport Ave & Wrightwood Ave,TA1307000113,41.928773,-87.663913,41.928773,-87.663913,casual,1492.068150
83601,DC66F5A5A4E3A460,classic_bike,2024-06-02 18:07:28.042,2024-06-03 18:31:22.024,Ogden Ave & Chicago Ave,TA1305000020,State St & Chicago Ave,21544,41.896362,-87.654061,41.896617,-87.628579,member,1463.899700
83992,924768DB873351DE,classic_bike,2024-06-19 16:44:09.180,2024-06-20 16:50:42.010,DuSable Lake Shore Dr & North Blvd,LF-005,Halsted St & Willow St,TA1307000166,41.911722,-87.626804,41.913865,-87.648755,casual,1446.547167

In [32]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
0,CDE6023BE6B11D2F,electric_bike,2024-06-11 17:20:06.289,2024-06-11 17:21:39.464,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual,1.552917
1,462B48CD292B6A18,electric_bike,2024-06-11 17:19:21.567,2024-06-11 17:19:36.377,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual,0.246833
2,9CFB6A858D23ABF7,electric_bike,2024-06-11 17:25:27.089,2024-06-11 17:30:13.035,NaN,NaN,NaN,NaN,41.93,-87.65,41.94,-87.65,casual,4.765767
3,6365EFEB64231153,electric_bike,2024-06-11 11:53:50.769,2024-06-11 12:08:13.382,NaN,NaN,NaN,NaN,41.88,-87.64,41.88,-87.64,casual,14.376883
4,BA0323C33134CBA8,electric_bike,2024-06-11 00:11:08.237,2024-06-11 00:11:22.998,NaN,NaN,NaN,NaN,41.94,-87.64,41.94,-87.64,casual,0.246017

In [33]:
df_normal = df[(df['ride_length'] > 0) & (df['ride_length'] <= 1440)].copy()

In [34]:
df_normal.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5622419 entries, 0 to 5628846
Data columns (total 14 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          datetime64[ns]
 3   ended_at            datetime64[ns]
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
 13  ride_length         float64
dtypes: datetime64[ns](2), float64(5), object(7)
memory usage: 643.4+ MB

In [35]:
df_normal.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
0,CDE6023BE6B11D2F,electric_bike,2024-06-11 17:20:06.289,2024-06-11 17:21:39.464,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual,1.552917
1,462B48CD292B6A18,electric_bike,2024-06-11 17:19:21.567,2024-06-11 17:19:36.377,NaN,NaN,NaN,NaN,41.89,-87.65,41.89,-87.65,casual,0.246833
2,9CFB6A858D23ABF7,electric_bike,2024-06-11 17:25:27.089,2024-06-11 17:30:13.035,NaN,NaN,NaN,NaN,41.93,-87.65,41.94,-87.65,casual,4.765767
3,6365EFEB64231153,electric_bike,2024-06-11 11:53:50.769,2024-06-11 12:08:13.382,NaN,NaN,NaN,NaN,41.88,-87.64,41.88,-87.64,casual,14.376883
4,BA0323C33134CBA8,electric_bike,2024-06-11 00:11:08.237,2024-06-11 00:11:22.998,NaN,NaN,NaN,NaN,41.94,-87.64,41.94,-87.64,casual,0.246017

In [37]:
print("Số dòng trước khi lọc:", df.shape[0])
print("Số dòng sau khi lọc:", df_normal.shape[0])

Số dòng trước khi lọc: 5628847
Số dòng sau khi lọc: 5622419

In [38]:
# Số dòng loại bỏ
5628847-5622419

6428

In [39]:
df_normal.drop(columns=['ride_length'], inplace=True)

In [40]:
# Lưu tập dữ liệu đã xử lý
df_normal.to_csv("12month_trip_data_cleaned.csv", index = False)